{
    "remarks": "💦 BPB - Domain_1 : 2096",
    "log": {
        "loglevel": "warning"
    },
    "dns": {
        "hosts": {
            "geosite:category-ads-all": "127.0.0.1",
            "geosite:category-ads-ir": "127.0.0.1",
            "geosite:category-porn": "127.0.0.1"
        },
        "servers": [
            "https://94.140.14.14/dns-query"
        ],
        "tag": "dns"
    },
    "inbounds": [
        {
            "port": 2080,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": true,
                "userLevel": 8
            },
            "sniffing": {
                "destOverride": [
                    "http",
                    "tls"
                ],
                "enabled": true,
                "routeOnly": true
            },
            "tag": "socks-in"
        },
        {
            "port": 2081,
            "protocol": "http",
            "settings": {
                "auth": "noauth",
                "udp": true,
                "userLevel": 8
            },
            "sniffing": {
                "destOverride": [
                    "http",
                    "tls"
                ],
                "enabled": true,
                "routeOnly": true
            },
            "tag": "http-in"
        },
        {
            "listen": "127.0.0.1",
            "port": 6450,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "1.1.1.1",
                "network": "tcp,udp",
                "port": 53
            },
            "tag": "dns-in"
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "104.19.62.86",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "flow": "",
                                "id": "89b3cbba-e6ac-485a-9481-976a0415eab9",
                                "level": 8,
                                "security": "auto"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "sockopt": {
                    "dialerProxy": "fragment",
                    "tcpKeepAliveIdle": 100,
                    "tcpNoDelay": true
                },
                "tlsSettings": {
                    "allowInsecure": false,
                    "fingerprint": "chrome",
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "serverName": "pANeLVpN.PagES.dEV"
                },
                "wsSettings": {
                    "headers": {
                        "Host": "pAnelvPn.pages.Dev"
                    },
                    "path": "/5GEKTAUIr8TJHKfa?ed=2560"
                }
            },
            "tag": "proxy"
        },
        {
            "tag": "fragment",
            "protocol": "freedom",
            "settings": {
                "fragment": {
                    "packets": "tlshello",
                    "length": "100-200",
                    "interval": "5-10"
                }
            },
            "streamSettings": {
                "sockopt": {
                    "tcpKeepAliveIdle": 100,
                    "tcpNoDelay": true
                }
            }
        },
        {
            "protocol": "dns",
            "tag": "dns-out"
        },
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "settings": {
                "response": {
                    "type": "http"
                }
            },
            "tag": "block"
        }
    ],
    "policy": {
        "levels": {
            "8": {
                "connIdle": 300,
                "downlinkOnly": 1,
                "handshake": 4,
                "uplinkOnly": 1
            }
        },
        "system": {
            "statsOutboundUplink": true,
            "statsOutboundDownlink": true
        }
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "inboundTag": [
                    "dns-in"
                ],
                "outboundTag": "dns-out",
                "type": "field"
            },
            {
                "ip": [
                    "8.8.8.8"
                ],
                "outboundTag": "direct",
                "port": "53",
                "type": "field"
            },
            {
                "domain": [
                    "geosite:category-ads-all",
                    "geosite:category-ads-ir",
                    "geosite:category-porn"
                ],
                "outboundTag": "block",
                "type": "field"
            },
            {
                "outboundTag": "proxy",
                "type": "field",
                "network": "tcp,udp"
            }
        ]
    },
    "stats": {}
}
